import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mango Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="logo-box">
          <Link href="./" className="logo">
            <Image
              src="/mango.svg"
              alt="mango logo"
              width={144}
              height={26}
              priority
            />
          </Link>
          {children}
        </div>
      </body>
    </html>
  );
}
